openapi: 3.0.0
info:
  title: Appointments API
  description: An API for managing medical appointments in a hospital
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /appointments:
    get:
      summary: Get all appointments
      responses:
        '200':
          description: A list of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: The created appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: The doctor with the given ID was not found
  /appointments/{id}:
    get:
      summary: Get an appointment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The appointment with the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: The appointment with the given ID was not found
    put:
      summary: Update an appointment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: The updated appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: The doctor with the given ID was not found
        '404':
          description: The appointment with the given ID was not found
    delete:
      summary: Delete an appointment by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The deleted appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
        patientName:
          type: string
        doctorId:
          type: integer
        appointmentTime:
          type: string
          format: date-time